

function Cookies(){
  return(
    <section>
      <h2 className="main__title">COOKIES</h2>
      <div className="info__container container">
        <h4 className="info__title">¿Para que utilizamos las cookies?</h4>
        <p className="info__paragraph">Podemos utilizar cookies: para recopilar datos anónimos sobre el comportamiento de los usuarios en el Sitio Web. También podemos captar información del Sitio Web desde el cual Ud. ha llegado al Sitio Web y hacia dónde se dirige así como algunos datos demográficos por ejemplo, la ubicación del usuario. Podemos usar esos datos para analizar el comportamiento del usuario a través de múltiples sitios; para clasificar los grupos de usuarios sobre una base anónima en base a los datos demográficos y / o de comportamiento y usar esto para, orientar nuestra publicidad a usuarios de cookies en los sitios web de terceros y sitios web de UMG, y utilizar esos datos para permitir a compañías de publicidad comportamental dirigir la publicidad a usuarios de cookies clasificados ya sea en relación con la colocación de publicidad que UMG ha comprado / colocado orientada a los usuarios en nombre de terceros o respecto de la publicidad comprada / colocada por terceras partes y dirigida a grupos de cookies que UMG ha vendido a estos terceros. Algunos de nuestros Sitios pueden utilizar Google AdSense para publicar anuncios. Cuando ve o hace clic en un anuncio se establecerá una cookie para mejorar la provisión de anuncios que puedan ser de interés para usted sobre este y otros sitios web. Algunos de nuestros Sitios Web también permiten colocar las cookies y otras tecnologías en su navegador por nuestro socio de publicidad RadiumOne. RadiumOne sirve anuncios que se muestren en algunos de nuestros países. Para saber más acerca de qué información recopila RadiumOne, cómo se utiliza esa información, lo que hace para proteger esa información y las opciones de recopilación y uso de esa información incluyendo la deshabilitación, por favor visite: http: // RadiumOne.com / sobre / privacy.html</p>
        <h4 className="info__title">¿Cómo puedo configurar mis cookies? ¿Cómo puedo eliminarlas?</h4>
        <p className="info__paragraph">Usted no está obligado a admitir una cookie nuestra, o de cualquier otro Sitio Web, y puede modificar su navegador para que no admita cookies, de acuerdo con lo previsto por la ley, pediremos siempre su consentimiento previo para el uso de cookies, salvo en el caso de las estrictamente necesarias para la prestación de un servicio solicitado por su parte y salvo que el consentimiento haya sido facilitado por su parte mediante el uso de los parámetros adecuados del navegador, durante la instalación o actualización del mismo. Si bien esta opción de bloqueo de Cookies en su navegador puede no permitirle el uso pleno de todas las funcionalidades del Website Ud. Puede deshabilitar la cookie de Google AdSense visitando: http://www.google.com/privacy_ads.html. Para bloquear el uso de cookies de RadiumOne por favor ver: http://www.radiumone.com/about/privacy.html#opting_out. Puede permitir, bloquear o eliminar las cookies instaladas en su equipo mediante la configuración de las opciones de su navegador de Internet. A continuación le explicamos cómo: Chrome: Desde http://support.google.com/chrome/bin/answer.py?hl=es&answer=95647 o Explorer: Desde http://windows.microsoft.com/es-es/windows7/how-tomanage-cookies-in-internet-explorer-9 o Firefox: Desde http://support.mozilla.org/es/kb/habilitar-y-deshabilitarcookies-que-los-sitios-we o Safari: Desde http://support.apple.com/kb/ph5042 Si rechaza la instalación de cookies podrá seguir usando el Sitio Web, aunque el uso de algunos de sus servicios podrá ser limitado y por tanto su experiencia en nuestro sitio web resultar menos satisfactoria. Existen herramientas de terceros, disponibles on-line, que permiten a los usuarios detectar las cookies en cada sitio web que visita y gestionar su desactivación. Para más información sobre la gestión de las cookies, puede dirigirse a www.allaboutcookies.org o visitar www.youronlinechoices.eu</p>
        <h4 className="info__title">Otras tecnologías de seguimiento</h4>
        <p className="info__paragraph">Web Beacons: nosotros, o nuestros socios, podemos emplear una tecnología de software llamada Web Beacons también conocida como Clear Gifs, Web Bugs o píxels, que nos ayuda a entender qué contenido es efectivo, por ejemplo que número de usuarios han visitado esas páginas. Los Web Beacons son pequeños gráficos con un identificador único, con igual función que las cookies, y se utilizan para hacernos saber cuándo el contenido se ve. En contraste con las cookies, que se almacenan en el disco duro de la computadora de un usuario, los Web Beacons se incrustan invisiblemente en las páginas Web. Nosotros o nuestros socios podemos vincular la información recogida por los Web Beacons con otra información que recolectemos sobre Ud.</p>
      </div>
    </section>
  )
}

export default Cookies