

function Privacidad(){
  return(
    <section>
      <h2 className="main__title">COOKIES</h2>
      <div className="info__container container">
        <h4 className="info__title">Quiénes somos</h4>
        <p className="info__paragraph">Este Sitio lo administra Universal Music Spain, S.L.U. C/ Torrelaguna, 64 28043 Madrid en adelante «nosotros», responsable del tratamiento de datos personales en virtud de la ley de protección de datos aplicable. Es posible que compartamos sus datos personales con UMG Recordings Services Inc., sita en 2220 Colorado Avenue, Santa Monica, California EE. UU., en calidad de responsable del tratamiento independiente al amparo de la ley de protección de datos aplicable. Tanto Universal Music Spain, S.L.U. como UMG Recordings Services Inc. efectúan, por separado, las declaraciones que esta Política de privacidad contiene y con ese fin, siempre que sea necesario, todas las referencias que se hagan en esta Política de privacidad a «nosotros» deberán considerarse referencias a UMG Recordings Services Inc. El término «empresas de UMG», según se utilice en esta Política de privacidad, incluye todas las entidades controladas por UMG y que controlen a esta o estén controladas conjuntamente por un tercero, incluyendo filiales, empresas conjuntas y demás entidades en las que UMG tenga una participación sustancial.</p>
        <h4 className="info__title">Contacto</h4>
        <p className="info__paragraph">Todas las preguntas, comentarios y solicitudes relacionadas con esta Política de privacidad serán bienvenidas haciendo clic aquí, o por correo postal a la dirección que proceda, la cual se ha especificado anteriormente. Usted puede ponerse en contacto con el delegado de protección de datos de UMG haciendo clic aquí, o por correo electrónico en la siguiente dirección: privacy.officer@umusic.com. Para preguntas, comentarios o solicitudes que no estén relacionadas con esta Política de privacidad, diríjase a nuestro apartado de preguntas frecuentes, en concreto a la sección de contacto con UMG.</p>
        <h4 className="info__title">Información que podríamos recoger de otras fuentes</h4>
        <p className="info__paragraph">También colaboramos estrechamente con terceros incluyendo, p. ej., socios comerciales, subcontratistas de servicios técnicos, de pago y de distribución, redes publicitarias, proveedores analíticos, redes sociales como Facebook y Twitter, proveedores de búsqueda de información, agencias de referencia crediticia, terceros que permiten funcionalidades de registro e integración de redes sociales, etc. y es posible que recibamos de éstos información sobre usted. Si usted decide utilizar los servicios disponibles en este Sitio o en otros sitios web de UMG que sirvan para conectarle a perfiles, cuentas o servicios en línea incluyendo cuentas en redes sociales, las «Cuentas conectadas», es posible que recopilemos cualquier información que usted nos permita a través de la configuración de esas Cuentas conectadas. Por ejemplo, si usted se conecta a nuestro Sitio utilizando su cuenta de Facebook y decide permitir que Facebook comparta su perfil con nosotros, es posible que nosotros recopilemos esa información. La información que recibimos de las Cuentas conectadas incluye la dirección de correo electrónico, nombre y apellido, ubicación ciudad y país, sexo, fecha de nacimiento, gustos, publicaciones o demás actividad social. Tenga a bien revisar la configuración de privacidad de su Cuenta conectada para controlar la información que se nos proporciona a nosotros a través de esta opción. Si usted solicita un empleo a UMG, es posible que, en lo que a su solicitud de empleo respecta, utilicemos la información que facilite para comunicarse con terceros, en la máxima medida que permita la legislación, incluyendo para verificar sus credenciales, historia laboral, referencias, comprobación de antecedentes o con otros fines relacionados con la solicitud de empleo.</p>
        <h4 className="info__title">Conservación y cesión de datos</h4>
        <p className="info__paragraph">Toda la información que proporcione la pueden tratar y almacenar, ceder o acceder a ella entidades de todo el mundo, tal y como se describe en esta política. Adoptaremos todas las medidas necesarias para asegurar que sus datos se tratan de forma segura y de acuerdo con esta Política de privacidad. Hemos introducido técnicas y organizativas destinadas a salvaguardar la información que recogemos en este Sitio. Lamentablemente, la transmisión de información a través de Internet no es completamente segura. Aunque haremos todo lo posible para proteger sus datos personales, no podemos garantizar la seguridad de sus datos transmitidos a nuestro Sitio; cualquier transmisión es bajo su propia responsabilidad.</p>
        <h4 className="info__title">Cookies</h4>
        <p className="info__paragraph">Nuestro Sitio utiliza cookies y otras tecnologías de seguimiento para diferenciarlo de otros usuarios de nuestro Sitio. Esto nos ayuda a proporcionarle una buena experiencia al navegar por nuestro Sitio y también nos permite mejorarlo. Para obtener información detallada sobre las cookies y otras tecnologías que utilizamos, así como para conocer los fines para los que las usamos, diríjase a nuestra política de cookies que encontrará a continuación.</p>
        <h4 className="info__title">Redes sociales y otros terceros</h4>
        <p className="info__paragraph">Es posible que parte del contenido, publicidad y prestaciones de nuestro Sitio sea facilitado por terceros no vinculados a nosotros. Por ejemplo, es posible que tenga la oportunidad de registrarse en nuestro Sitio por medio de servicios de registro, tales como Facebook Connect o un proveedor de Open ID. Estos servicios autentificarán su identidad y le facilitarán la posibilidad de compartir con nosotros determinados datos personales. Determinados servicios, como Facebook Connect, le dan la opción de publicar en su página de perfil información sobre las actividades que lleve a cabo en este Sitio, para así compartirla con otras personas dentro de su red de contactos. También es posible que terceros anunciantes tengan presencia en nuestros Sitios. Es posible que tanto éstos que hemos mencionado como otros terceros recopilen o reciban determinada información acerca del uso que usted haga de nuestros Sitios, incluyendo por medio del uso de cookies y otras tecnologías de internet; esta información podría recopilarse a lo largo del tiempo y combinarse con información recopilada en otras páginas web y servicios en línea. Algunas de estas empresas participan en programas desarrollados por la industria, destinados a ofrecer a los consumidores distintas opciones sobre si recibir o no publicidad dirigida. Si lo desea, puede visitar estas páginas web, gestionadas por la Network Advertising Initiative iniciativa publicitaria en la red, Digital Advertising Alliance alianza de publicidad digital y la European Interactive Digital Advertising Alliance.</p>
      </div>
    </section>
  )
}

export default Privacidad